name: "Website Slider Update"

on:
  schedule:
    - cron: "0 18 * * SUN" # Sundays at 7pm/8pm CE(S)T
  push:
    branches: [main]

jobs:
  schedule:
    name: Codecept and Google Calendar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # to have the repo content actually available
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm ci
      - env:
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
          SERVICE_ACCOUNT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
          PASSWORD_WP_ADMIN: ${{ secrets.PASSWORD_WP_ADMIN }}
          USERNAME_WP_ADMIN: ${{ secrets.USERNAME_WP_ADMIN }}
          WP_SLIDER_URL: ${{ secrets.WP_SLIDER_URL }}
        run: npm run update-slider
