name: "Website Slider Update"

on:
  schedule:
    - cron: "0 18 * * SUN" # Sundays at 7pm/8pm CE(S)T
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  schedule:
    name: Codecept and Google Calendar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # to have the repo content actually available
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - env:
          # Dependabot PRs have Actions secrets not available.
          # See secrets in Dependabot runs: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#accessing-secrets
          # Why secrets are not available: https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
          SERVICE_ACCOUNT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
          PASSWORD_WP_ADMIN: ${{ secrets.PASSWORD_WP_ADMIN }}
          USERNAME_WP_ADMIN: ${{ secrets.USERNAME_WP_ADMIN }}
          WP_SLIDER_URL: ${{ secrets.WP_SLIDER_URL }}
        run: npm run update-slider
